### ISSUE TITLE
more validation

### ISSUE THREAD

**Issue by jdv** [jonathanstowe/Test-META#1]
It would be nice if we could provide things like:

1.  Names.  Example being Foo::Bar vs Foo-Bar in a field like name.
2.  Versions.  Example being v1.2 vs 1.2 in fields like perl or version.

**Comment by jonathanstowe** [comment]
Hi,
I think I would like to deal with this as two separate things.  

The name thing, whilst generally sensible, should have a flag to turn it off (like :relaxed-name or some such,) as while it almost certainly is a mistake in most cases, it is technically valid and the author may have their own reasons for creating a module with a hyphen in the name which I would rather not second guess.

Despite the S22 saying that the version should be a "version literal" (and thus implies v1.2), it seems that all existing software (e.g. "panda" etc) will accept them interchangeably, so the META6 module does too currently. I would suggest that this should, in the interim, be considered optional and switched on with a :strict-version or something.

The intention of the module was more to check that the META file would actually work rather than to attempt some notional standards enforcement (which is why it knows about customary fields as well as the specced ones,)

Thanks for your input.

**Comment by jonathanstowe** [comment]
I think with version thing that everyone is now agreeing that "version literal" should not contain a "v", so I'm going to turn this into a warning in META6 *and* if the meta6 version is greater than v0 (the default) then it will be a test failure.  This will go in the next version of Test::META/META6 (which I may make tomorrow)

**Comment by jonathanstowe** [comment]
So, if the specified meta6 version is greater than the default 0 then a v prefix to versions is a fail.
Unless :relaxed-name is specified to meta-ok then a hypen in 'name' is a fail

Hope that helps
