### ISSUE TITLE
Could not find META6:ver...

### ISSUE THREAD

**Issue by nkh** [jonathanstowe/Test-META#27]
worked till I update to latest rakudo
* 3e078d4 space after import modulename shall not explode the compiler  

t/02_META.t .................. ===SORRY!===
Could not find META6:ver<0.0.4..*> at line 66 in:
    /home/nadim/nadim/devel/repositories/perl_modules/P6-Data-Dump-Tree/lib
    /home/nadim/nadim/devel/repositories/perl_modules/P6-Data-Dump-Tree/t
    /home/nadim/.perl6
    /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/site
    /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6/vendor
    /home/nadim/nadim/devel/repositories/rakudo/install/share/perl6
    CompUnit::Repository::AbsolutePath<94783924925024>
    CompUnit::Repository::NQP<94783881701408>
    CompUnit::Repository::Perl5<94783881701448>
Dubious, test returned 1 (wstat 256, 0x100)

**Comment by jonathanstowe** [comment]
Hi,
this was fixed in the https://github.com/jonathanstowe/Test-META/commit/1e0e9beca4f96d0c3457be9ef67f9b175ff48be5 so you will need to upgrade to a more recent version of Test::META.

**Comment by nkh** [comment]
I did a zef install Test::META and it told me I had the latest version installed.

BTW, we were discussing you on #perl6 and the consensus was thta you were missed and that we'd like to see you more ;)

**Comment by jonathanstowe** [comment]
I'm not entirely sure how often zef refreshes its metadata, but the fix is definitely in the https://github.com/jonathanstowe/Test-META/releases/tag/v0.0.10  (admittedly I have been known to make a fix and then forget to push it to github, but not in this case ;-)

With the IRC thing I've been using up a large part of my limited time and brain power with the day job this year unfortunately :)

**Comment by nkh** [comment]
Hi, we found how to fix it:

zef uninstall JSON::Class JSON::Marshal META6 Test::META 

then

zef install Test::META
